# fly.toml app configuration file generated for pb-long-fog-5528 on 2025-01-18T21:00:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pb-long-fog-5528'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"